version: '3.7'
services:
  app:
    build: .
    networks:
      - database
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    networks:
      - database
    ports:
      - "5431:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:

networks:
  database: